#ifndef IUIWIDGETGDEF_H
#define IUIWIDGETGDEF_H
namespace UI {
typedef enum{
  COL_PAGE_TREE_NAME,
  COL_PAGE_TREE_VALUE,
  COL_PAGE_TREE_TYPE,
  COL_PAGE_TREE_UNIT,
  COL_PAGE_TREE_DLIMIT,
  COL_PAGE_TREE_ULIMIT,
  COL_PAGE_TREE_INTRODUCT,
  COL_PAGE_TREE_ADDR,
  COL_PAGE_TREE_SCALE
}PageTreeColumn;
}

#endif // IUIWIDGETGDEF_H

