#ifndef PLOTUNITGRAPH_GLOBAL_H
#define PLOTUNITGRAPH_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLOTUNITGRAPH_LIBRARY)
#  define PLOTUNITGRAPHSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLOTUNITGRAPHSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLOTUNITGRAPH_GLOBAL_H
