#ifndef SDTGRAPHICSITEMS_GLOBAL_H
#define SDTGRAPHICSITEMS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SDTGRAPHICSITEMS_LIBRARY)
#  define SDTGRAPHICSITEMSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SDTGRAPHICSITEMSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IUIWIDGET_GLOBAL_H
