#ifndef MOTIONVELOCITY_GLOBAL_H
#define MOTIONVELOCITY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MOTIONVELOCITY_LIBRARY)
#  define MOTIONVELOCITYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MOTIONVELOCITYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MOTIONVELOCITY_GLOBAL_H
