#ifndef MOTIONPOSITION_GLOBAL_H
#define MOTIONPOSITION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MOTIONPOSITION_LIBRARY)
#  define MOTIONPOSITIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MOTIONPOSITIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MOTIONPOSITION_GLOBAL_H
